apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-kind-kluster-app
  namespace: first-kind-kluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-kind-kluster-app
  template:
    metadata:
      labels:
        app: first-kind-kluster-app
    spec:
      containers:
      - name: first-kind-kluster-app
        image: hashicorp/http-echo
        args:
        - "-text=SUCCESS: You reached the dummy app on your local cluster!"
        ports:
        - containerPort: 5678
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"