apiVersion: v1
kind: Service
metadata:
  name: first-kind-kluster-service
  namespace: first-kind-kluster
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: first-kind-kluster-app
 