apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-kind-kluster-ingress
  namespace: first-kind-kluster
spec:
  ingressClassName: nginx
  rules:
  - host: demo.first-kind-kluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: first-kind-kluster-service
            port:
              number: 80